# https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/Build+a+Helm+chart+for+EKS
# https://github.com/external-secrets/kubernetes-external-secrets#add-a-secret
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: pghero-helm102
  name: basic-auth-secrets
  labels:
    app.kubernetes.io/name: pghero-helm102
  annotations:
    #app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/sync-options: Replace=true
    meta.helm.sh/release-name: pghero-helm102
spec:
  backendType: systemManager
  data:
    - key: /dsva-vagov/vets-api/prod/vets_api_pghero_basic_auth
      name: pghero-basic-auth-secrets
