# https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/Build+a+Helm+chart+for+EKS
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pghero-cm
  namespace: {{ .Release.Namespace }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/sync-options: Replace=true
    meta.helm.sh/release-name: {{ .Release.Namespace }}
data:
  pghero.yml: |
    databases:
      development:
        url: 'postgres://vets_api:<%=ENV["PG_DEV_DB_PASSWORD"]%>@dsva-vets-api-dev.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com:5432/dsva_vets_api_dev?pool=16'
        capture_query_stats: primary
        # System stats
        # aws_db_instance_identifier: my-instance
        # gcp_database_id: my-project:my-instance
        # azure_resource_id: my-resource-id

      # Add more databases
      # other:
      #   url: <%= ENV["OTHER_DATABASE_URL"] %>

    # Minimum time for long running queries
    # long_running_query_sec: 60

    # Minimum average time for slow queries
    # slow_query_ms: 20

    # Minimum calls for slow queries
    # slow_query_calls: 100

    # Minimum connections for high connections warning
    # total_connections_threshold: 500

    # Statement timeout for explain
    # explain_timeout_sec: 10

    # Time zone
    # time_zone: "Pacific Time (US & Canada)"
