---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pghero
  labels:
    app.kubernetes.io/name: pghero
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pghero
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pghero
    spec:
      containers:
        - name: pghero
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: Always
          env:
            {{- range .Values.web.envVars }} # Iterating over a Complex Structure
            - {{ . | toYaml | nindent 12 -}}
            {{- end }}
          volumeMounts:
            - name: pghero-configmap
              mountPath: /app/config/pghero.yml
              readOnly: true
              subPath: pghero.yml
          ports:
            - name: dashboard
              containerPort: 8080
      volumes:
        - name: pghero-configmap
          configMap:
            defaultMode: 0644
            name: pghero
