---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pghero-deploy
  labels:
    app.kubernetes.io/name: pghero
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pghero
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pghero
    spec:
      containers:
        - image: "{{ .Values.image.value }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # name: {{ .Values.appName }}-web
          name: pghero
          # env:
          volumeMounts:
            - name: pghero-configmap
              mountPath: /app/config/pghero.yml
              readOnly: true
              subPath: pghero.yml
          ports:
            - name: dashboard
              containerPort: 8080
      volumes:
        - name: pghero-configmap
          configMap:
            defaultMode: 0644
            name: pghero
