apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: pghero-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: "{{ .Values.app.name }}-{{ .Values.app.env }}"
spec:
  backendType: systemManager
  data:
    - key: /dsva-vagov/vets-api/dev/database_password
      name: pg-dev-dbpassword

