# https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/Build+a+Helm+chart+for+EKS
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
---
apiVersion: v1
kind: Service
metadata:
  namespace: pghero-helm102
  name: pghero-svc
  labels:
    app.kubernetes.io/name: pghero-helm102
  annotations:
    #app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/sync-options: Replace=true
    meta.helm.sh/release-name: pghero-helm102
spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: 9090
      name: svc9090
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

  selector:
    app.kubernetes.io/name: pghero-helm102
