# Default values for pghero-helm102.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "pghero-helm102"

app:
  name: "pghero-helm102"
  env: "dev"

image:
  value: "008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/pghero"
  tag: "pghero-v3.0.0"
  pullPolicy: Always
  
web:
  externalDns:
    dnsName: pghero-helm102-dev.vfs.va.gov
    recordTTL: 180
    target: traefik-dev.vfs.va.gov 
  ingress:
    enabled: true
    entryPoint: web
    route:
      kind: Rule
      match: Host(`dnsName`) && PathPrefix(`/`)
      priority: 10
      service:
        name: svc9090
        port: 9090
      middleware:
        name: traefik-basic-auth
  envVars:
    - name: PG_DEV_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pghero-secrets
          key: pg-dev-dbpassword
    - name: PGHERO_STATS_DATABASE_URL
      value: "postgres://vets_api:$(PG_DEV_DB_PASSWORD)@dsva-vets-api-dev.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com:5432/dsva_vets_api_dev?pool=16"

cronjobs:
  - name: capture-space-stats
    schedule: "0 8 * * *"
    rake_task: "bin/rake pghero:capture_space_stats"
  - name: capture-query-stats
    schedule: "0 8 * * *"
    rake_task: "bin/rake pghero:capture_query_stats"
  - name: clean-query-stats       
    schedule: "0 0 1,15 * *"
    rake_task: "bin/rake pghero:clean_query_stats"
