# Default values for pghero-helm102.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: ""
image:
  value: ""
  tag: ""
  pullPolicy: Always
  
#Web configuration
web:
  externalDns:
    dnsName: ""
    recordTTL: 180
    targets: ""
