# Default values for pghero-helm102.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: ""
image:
  value: ""
  tag: ""
  pullPolicy: Always
  
web:
  externalDns:
    dnsName: ""
    recordTTL: 180
    targets: ""
  ingress:
    enabled: true
    entryPoints: web
      routes:
        - kind: Rule
          match: Host(`pghero-helm102-dev.vfs.va.govv`) && PathPrefix(`/`)
          priority: 10
          services:
            - name: pghero
              port: 9090
          middlewares:
            - name: pghero-basic-auth
 
