name: Mirror pghero image to ECR when versions.json/Dockerfile changes

on:
 push:
   #   branches:
   #     - master
   paths:
     - ".github/workflows/mirror-images.yml"
 schedule:
   - cron: '0 0 1,15 * *'
 workflow_dispatch:

jobs:
  define-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Define pghero images
        run: |
          IMAGES=$(cat << EOF
          [  
            {
              name: "pghero",
              version: "v2.8.1",
              repo: "ankane/pghero"
            }
          ]
          EOF
          )
          IMAGES="${IMAGES//'%'/'%25'}"
          IMAGES="${IMAGES//$'\n'/'%0A'}"
          IMAGES="${IMAGES//$'\r'/'%0D'}"
          echo "::set-output name=images::$IMAGES"
        id: define-images
    outputs:
      images: ${{ steps.define-images.outputs.images }}

  mirror:
    runs-on: ubuntu-20.04
    needs: define-images
    strategy:
      matrix:
        images: ${{ fromJson(needs.define-images.outputs.images) }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and push ${{ matrix.images['name']}} images to ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: '008577686731'
          repo: dsva/pghero
          region: us-gov-west-1
          tags: "${{ matrix.images['name']}}-${{ matrix.images['version'] }}"
          dockerfile: Dockerfile
          extra_build_args: "--build-arg APP_VERSION=${{ matrix.images['version'] }} --build-arg REPO=${{ matrix.images['repo'] }}"
