name: Mirror pghero image to ECR when versions.json/Dockerfile changes

on:
 push:
   #   branches:
   #     - master
   paths:
     - ".github/workflow/mirror-images.yml"
 schedule:
   - cron: '0 0 1,15 * *'
 workflow_dispatch:

jobs:
  define-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Define pghero images
        run: |
          IMAGES=$(cat << EOF
          [  
            {
              name: "pghero",
              version: "v2.8.1",
              repo: "ankane/pghero"
            }
          ]
          EOF
          )
          echo "IMAGES<<EOF" >> $GITHUB_ENV
          echo "$IMAGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  mirror:
    runs-on: ubuntu-20.04
    needs: define-images
    strategy:
      matrix:
        versions: ${{ fromJson(env.IMAGES) }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and push argo images to ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: '008577686731'
          repo: dsva/pghero
          region: us-gov-west-1
          tags: "${{ matrix.versions['name']}}-${{ matrix.versions['version'] }}"
          dockerfile: Dockerfile
          extra_build_args: "--build-arg APP_VERSION=${{ matrix.versions['version'] }} --build-arg REPO=${{ matrix.versions['repo'] }}"
